#!/bin/bash

export INPUT_INVENTORIES_DIR="$GENERIC_RESOURCES_DIR/portfolio/inventories"
export INPUT_DASHBOARDS_DIR="$GENERIC_RESOURCES_DIR/portfolio/dashboards"
export INPUT_REPORTS_DIR="$GENERIC_RESOURCES_DIR/portfolio/reports"
export INPUT_ADVISOR_INVENTORIES_DIR="$GENERIC_RESOURCES_DIR/portfolio/inventories"
export OUTPUT_GENERIC_RESOURCES_DIR="$PORTFOLIO_DIR"
