#!/bin/bash

export INPUT_INVENTORIES_DIR="$ADVISED_DIR_002"
export INPUT_DASHBOARDS_DIR="$ADVISED_DIR_002"
export INPUT_REPORTS_DIR="$REPORTED_DIR_002"
export INPUT_ADVISOR_INVENTORIES_DIR="$ADVISED_DIR_002"
export OUTPUT_GENERIC_RESOURCES_DIR="$PORTFOLIO_DIR_002"
