#!/bin/bash

export INPUT_INVENTORY_DIR="$TARGET_WORKSPACE_002_DIR/sample-product-1.0.0"
export INPUT_INVENTORY_PATH="05_advised"
export INPUT_SECURITY_POLICY_FILE="$EXTERNAL_WORKBENCH_DIR/policies/security-policy.json"
export INPUT_ADVISOR_INVENTORIES_DIR=""
export INPUT_DASHBOARDS_DIR="$ADVISED_DIR_002"
export INPUT_REPORTS_DIR="$REPORTED_DIR_002"
export OUTPUT_OVERVIEW_FILE="$PORTFOLIO_DIR_001/overview.html"
