#!/bin/bash

export MIRROR_TARGET_DIR="$EXTERNAL_VULNERABILITY_MIRROR_DIR"
export MIRROR_ARCHIVE_URL="$EXTERNAL_VULNERABILITY_MIRROR_URL"
export MIRROR_ARCHIVE_USERNAME="test_username"
export MIRROR_ARCHIVE_PASSWORD="test_password"
