#!/bin/bash

export INPUT_ASSET_DESCRIPTOR_PATH="asset-descriptor_GENERIC-vulnerability-report.yaml"
export INPUT_INVENTORY_FILE="$ADVISED_DIR_002/busybox-1.35.0-enriched.xlsx"
export OUTPUT_DOCUMENT_FILE="$REPORTED_DIR_002/busybox-1.35.0-vulnerability-report.pdf"
export OUTPUT_COMPUTED_INVENTORY_DIR="$REPORTED_DIR_002/computed"
export PARAM_REFERENCE_INVENTORY_DIR="$EXTERNAL_WORKBENCH_DIR/inventories/example-reference-inventory/inventory"
export PARAM_SECURITY_POLICY_FILE="$EXTERNAL_WORKBENCH_DIR/policies/security-policy/security-policy.json"
export PARAM_DOCUMENT_TYPE="VR"
export PARAM_ASSET_ID="sample-asset-id"
export PARAM_ASSET_NAME="sample-asset"
export PARAM_ASSET_VERSION="1.0.0"
export PARAM_PRODUCT_NAME="sample-product"
export PARAM_PRODUCT_VERSION="1.0.0"
export PARAM_PRODUCT_WATERMARK=""
export PARAM_OVERVIEW_ADVISORS="CERT_FR"
export PARAM_PROPERTY_SELECTOR_ORGANIZATION="metaeffekt"
export ENV_WORKBENCH_DIR="$EXTERNAL_WORKBENCH_DIR"
export ENV_VULNERABILITY_MIRROR_DIR="$EXTERNAL_VULNERABILITY_MIRROR_DIR/.database"