#!/bin/bash

export INPUT_ASSET_DESCRIPTOR_PATH="asset-descriptor_GENERIC-vulnerability-report.yaml"
export INPUT_INVENTORY_FILE="$AGGREGATED_DIR_001/sample-asset-1.0/sample-asset-1.0-inventory.xls"
export INPUT_REFERENCE_INVENTORY_FILE="$INTERNAL_WORKBENCH_DIR/inventories/example-reference-inventory/inventory/artifact-inventory.xls"
export OUTPUT_DOCUMENT_FILE="$REPORTED_DIR_001/asset-vulnerability-report.pdf"
export OUTPUT_COMPUTED_INVENTORY_DIR="$REPORTED_DIR_001/computed"
export PARAM_REFERENCE_INVENTORY_DIR="$INTERNAL_WORKBENCH_DIR/inventories/example-reference-inventory/inventory"
export PARAM_SECURITY_POLICY_FILE="$INTERNAL_WORKBENCH_DIR/policies/vulnerability-report/security-policy-02.json"
export PARAM_DOCUMENT_TYPE="VR"
export PARAM_ASSET_ID="sample-asset-id"
export PARAM_ASSET_NAME="sample-asset"
export PARAM_ASSET_VERSION="1.0.0"
export PARAM_PRODUCT_NAME="sample-product"
export PARAM_PRODUCT_VERSION="1.0.0"
export PARAM_PRODUCT_WATERMARK=""
export PARAM_OVERVIEW_ADVISORS="CERT_FR"
export PARAM_PROPERTY_SELECTOR_ORGANIZATION="metaeffekt"
export ENV_WORKBENCH_DIR="$EXTERNAL_WORKBENCH_DIR"
export ENV_VULNERABILITY_MIRROR_DIR="$EXTERNAL_VULNERABILITY_MIRROR_DIR/.database"