#!/bin/bash

export INPUT_ASSET_DESCRIPTOR_DIR="$EXTERNAL_WORKBENCH_DIR/descriptors"
export INPUT_ASSET_DESCRIPTOR_PATH="asset-descriptor_GENERIC-vulnerability-report.yaml"
export INPUT_INVENTORY_FILE="$AGGREGATED_DIR_001/sample-asset-1.0/sample-asset-1.0-inventory.xls"
export INPUT_REFERENCE_INVENTORY_FILE="$INTERNAL_WORKBENCH_DIR/inventories/example-reference-inventory/inventory/artifact-inventory.xls"
export INPUT_REFERENCE_LICENSE_DIR="$INTERNAL_WORKBENCH_DIR/inventories/example-reference-inventory/licenses"
export INPUT_REFERENCE_COMPONENT_DIR="$INTERNAL_WORKBENCH_DIR/inventories/example-reference-inventory/components"
export OUTPUT_DOCUMENT_FILE="$REPORTED_DIR_001/asset-vulnerability-report.pdf"
export OUTPUT_COMPUTED_INVENTORY_DIR="$REPORTED_DIR_001/computed"
export PARAM_SECURITY_POLICY_FILE="$EXTERNAL_WORKBENCH_DIR/policies/security-policy/security-policy.json"
export PARAM_TEMPLATE_DIR="$EXTERNAL_WORKBENCH_DIR/templates/report-template"
export PARAM_DOCUMENT_TYPE="VR"
export PARAM_DOCUMENT_LANGUAGE="en"
export PARAM_ASSET_ID="sample-asset-id"
export PARAM_ASSET_NAME="sample-asset"
export PARAM_ASSET_VERSION="1.0.0"
export PARAM_PRODUCT_NAME="sample-product"
export PARAM_PRODUCT_VERSION="1.0.0"
export PARAM_PRODUCT_WATERMARK=""
export PARAM_OVERVIEW_ADVISORS="CERT_FR"
export PARAM_PROPERTY_SELECTOR_ORGANIZATION="metaeffekt"
export ENV_KONTINUUM_PROCESSORS_DIR="$PROCESSORS_DIR"
export ENV_WORKBENCH_PROCESSORS_DIR="$EXTERNAL_WORKBENCH_DIR/processors"
export ENV_VULNERABILITY_MIRROR_DIR="$EXTERNAL_VULNERABILITY_MIRROR_DIR/.database"