#!/bin/bash

export INPUT_INVENTORY_FILE="$RESOURCES_DIR/example-001.xlsx"
export INPUT_INVENTORY_COMPARE_FILE="$RESOURCES_DIR/example-002.xlsx"
export INVENTORY_VERSION="example-001"
export INVENTORY_COMPARE_VERSION="example-002"
export OUTPUT_INVENTORY_DIR="$UTIL_DIR"
export SECURITY_POLICY_FILE="$RESOURCES_DIR/advise/security-policy.json"
